Fix small grammatical error in on-facebook-p2 message
mozilla/contain-facebook pull request #725
Opened 2021-02-05 06:58 UTC by euphemism

2021-02-05 07:19 UTC, flodolo reviewed
Ugh, that's definitely a typo. I'm OK with fixing also the other en-* variants, but flagging one of the devs for visibility.

I wonder if "need access to" is better than "need to access".

2021-02-05 07:53 UTC, euphemism commented
> Ugh, that's definitely a typo. I'm OK with fixing also the other en-* variants, but flagging one of the devs for visibility.
> 
> I wonder if "need access to" is better than "need to access".

I personally would have probably gone with "need access to," but I was bringing the message inline with the content of `onboarding2-p2`.

2021-04-15 01:29 UTC, peeteyg approved these changes

2021-04-15 05:05 UTC, flodolo commented
@peeteyg 

This is not a playground, don't go around messing with other people's work. Thanks.

2021-04-15 18:25 UTC, maxxcrawford commented
@flodolo Great call-out. By editing the existing string (and not making a new one) does that stop it from having to be localized else where?

2021-04-15 18:29 UTC, maxxcrawford requested changes
@euphemism Thanks for catching this error. 

@flodolo Thanks for breaking this to our attention!

2021-04-15 18:29 UTC, maxxcrawford commented on src/_locales/en-CA/messages.json
> +    "message": "These sites need to access your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
See the following suggestion. Please make these across all three strings. 

```suggestion
    "message": "These sites need access to your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
```

2021-04-15 18:29 UTC, maxxcrawford commented on src/_locales/en-GB/messages.json
> +    "message": "These sites need to access your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
```suggestion
    "message": "These sites need access to your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
```

2021-04-15 18:29 UTC, maxxcrawford commented on src/_locales/en/messages.json
> +      "message": "These sites need to access your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
```suggestion
      "message": "These sites need access to your Facebook identity (or know who you are) in order to work. This also means that Facebook can track everything you do on these sites.",
```

2021-04-15 18:30 UTC, flodolo commented
> @flodolo Great call-out. By editing the existing string (and not making a new one) does that stop it from having to be localized else where?

No, what counts is the string ID (`on-facebook-p2`), so we can merge this without impacting other existing localizations.

2021-04-28 17:52 UTC, merged