fix: Updated the FACEBOOK_DOMAINS array to include additional domains…
mozilla/contain-facebook pull request #943
Opened 2023-07-06 20:30 UTC by flightlesstux

Updated the FACEBOOK_DOMAINS array to include additional domains and sorted them alphabetically. Added the provided domains to the array and arranged them in ascending order for better organization and ease of reference.

2023-07-09 07:27 UTC, jeffguillaume approved these changes

2023-07-09 12:42 UTC, flightlesstux commented
Hi @jeffguillaume, thank you for your approval. Best! 🙏🏻

2023-07-11 20:01 UTC, NeckBeardPrince commented
@jeffguillaume  Need another approval

2023-07-15 03:41 UTC, jeffguillaume approved these changes
How have these domains been vetted? It looks like there are many additions.

2023-07-17 09:17 UTC, flightlesstux commented
> How have these domains been vetted? It looks like there are many additions.

Hi, I don't remember how I found them but we can check like below.

```
#!/bin/bash

# Domains list
domains=("accountkit.com" "acebook.com" "faacebook.com" "facebbook.com" "facebookcareers.com" "facebook.co" "facebook.com" "facebook.com.au" "facebook.com.mx" "facebook-dns.com" "facebookenterprise.com" "facebook-hardware.com" "facebook.it" "facebookmail.com" "facebook.net" "facebookrecruiting.com" "facebookstudy.com" "facebookvirtualassistant.com" "fb.audio" "fbcdn.net" "fb.com" "fbe2e.com" "fb.gg" "fbinfra.net" "fb.me" "fbpigeon.com" "fbsbx.com" "fbthirdpartypixel.com" "fb.watch" "fbwat.ch" "internet.org" "m-freeway.com" "parse.com" "wit.ai" "www.facebook.com" "fbcdn.com" "tfbnw.net" "facebook-web-clients.appspot.com" "fbcdn-profile-a.akamaihd.net" "fbsbx.com.online-metrix.net" "connect.facebook.net.edgekey.net" "facebookblueprint.com" "fburl.com" "internalfb.com" "cdninstagram.com" "instagramstatic-a.akamaihd.net" "instagramstatic-a.akamaihd.net.edgesuite.net" "messenger.com" "m.me" "messengerdevelopers.com" "facebook.messenger.com" "atdmt.com" "workplace.com" "www.workplace.com" "work.facebook.com" "onavo.com" "oculus.com" "oculusvr.com" "oculusbrand.com" "oculusforbusiness.com" "mapwith.ai" "mapillary.com" "oversightboard.com" "www.oversightboard.com" "bulletin.com" "facebookbrand.com" "metacareers.com" "meta.com" "metaque.st" "novi.com" "threads.net")

# Iterating through the domains list
for domain in ${domains[@]}; do
  # Get the IP address
  ip=$(dig +short $domain)
  
  # Print the IP address
  echo "$domain IP address: $ip"
  
  # Get the whois information
  whois_info=$(whois $ip | grep -i 'OrgName\|OrgId\|Address\|City\|StateProv\|PostalCode\|Country\|RegDate\|Updated\|Comment')

  # Print the whois information
  echo "$domain whois information: $whois_info"
  echo "--------------------------------------"
done
```

2023-07-25 15:07 UTC, maxxcrawford requested changes
@flightlesstux I love the single line break-up of the array. It's MUCH more readable. 

Can you break please break this one PR into TWO PRs? (One with the new array layout and a second one introducing the new domains) 

Adding extra domains can/may introduce unforeseen breakage. We are always extra cautious when adding domains, and we will need to independently verify Meta-ownership, etc. Thanks!

2024-01-07 03:48 UTC, kevinsumner commented
I ran into this with fb.watch today, so I created #959 and #960 to address the feedback here.

2026-09-11 17:41 UTC, closed without merging